# Generated by Django 3.0.7 on 2020-06-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showvideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default='hello', unique=True),
            preserve_default=False,
        ),
    ]
